### ISSUE TITLE
Argo tunnel support

### ISSUE THREAD

**Issue by karanpratapsingh** [cloudflare/node-cloudflare#100]
Is there argo tunnel support in this package? I can see it is available in the v4 api. Sorry if I missed it in the [docs](https://cloudflare.github.io/node-cloudflare/)

**Comment by terinjokes** [comment]
It was just added in b168f5d781672e75d7240c3caf71f7e2dfc36dbe, but it hasn't been released yet. Should hopefully be soon.

**Comment by karanpratapsingh** [comment]
Nice! thanks @terinjokes, also do you have a rough estimate in mind on the release?

**Comment by terinjokes** [comment]
Likely this week or Saturday. There's a few more PRs I wanted to get merged beforehand.

**Comment by karanpratapsingh** [comment]
Thanks @terinjokes

**Comment by ArielPrevu3D** [comment]
Would be awesome to get a new release for this package.

**Comment by smashah** [comment]
what's the hold up on this release?
