### ISSUE TITLE
Improve error catching

### ISSUE THREAD

**Issue by ririko5834** [cloudflare/node-cloudflare#101]
I think that instead of returning `Response code xxx (xxx)` errors when calls were not successful, JSON response should be parsed and error should be returned.

Example:
I wanted to add DNS record to my tk domain, I got this error `Response code 403 (Forbidden)`. I thought that there is some problem with my API and I couldn't investigate the problem. Then I called the API endpoint directly with CURL and I got this response:
```
{
    "result": null,
    "success": false,
    "errors": [{
        "code": 1038,
        "message": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
    }],
    "messages": []
}
```

The wrapper should display the error message instead of just request status.

**Comment by terinjokes** [comment]
The original response is available as the `respoonse` property of the error object.

**Comment by RaeesBhatti** [comment]
I think the error message should be the actual errors returned by the API. That would make things easier to debug for someone who's new without having to go find how to find the actual error.

**Comment by terinjokes** [comment]
I'll accept a PR to add documentation to the readme to explain the original response, if any, is available under the response property of the error.
