### ISSUE TITLE
Old `got` breaks runtime

### ISSUE THREAD

**Issue by vicary** [cloudflare/node-cloudflare#104]
The current dependent of `got@6.3.0` breaks runtime because it tries to require package.json in a extensionless mannar  `require('./package');`, more recent versions does not have this problem.

Would you please consider upgrading?

**Comment by terinjokes** [comment]
I'm unlikely to upgrade got, but yeah, I've been working on a branch to remove it.

**Comment by vicary** [comment]
Removing got is also a great option, thanks for the transparency and please take your time.

Do you by any chance have any workarounds in the mean time?
