### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by ShivamJoker** [cloudflare/node-cloudflare#110]
Would be great to have it fixed

(node:145390) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by cmdshepard** [comment]
This is due to the version of `got` being used.

Issue #104 mentions a pending migration away from `got. @terinjokes is migrating away from `got` still on your radar?

**Comment by ShivamJoker** [comment]
@terinjokes shouldn't it be as simple as updating the package or are there any breaking changes?

**Comment by terinjokes** [comment]
I didn't know this at the time I picked it, but pretty much every version of `got` is a breaking change, and I made the mistake of exposing too much of the API to external users.

**Comment by ShivamJoker** [comment]
@terinjokes it's been 3 months and still no updates on the library?

**Comment by holgersindbaek** [comment]
This issue seems to have broken the library. Since the new year, I've received a 400 response.

**Comment by rawpixel-vincent** [comment]
the deprecated warnings come from `timed-out` module
https://github.com/sindresorhus/timed-out/issues/28#[
](https://github.com/sindresorhus/timed-out/commit/5c7469321775e7d7cf07ddd85abc597cdf56d5ad)

would the maintainer accept a PR that pin timed-out to resolve from this commit ^
using `resolutions` field from package.json
