### ISSUE TITLE
require('cloudflare') is not a function

### ISSUE THREAD

**Issue by PraveenDev2007** [cloudflare/node-cloudflare#114]
I was trying to edit the dns for my domain manually using cloudfare for nodejs API.
But when I put the following code:
```
 var clouflareClient = require('cloudflare')({
    email: 'myemail@gmail.com',
    key: 'myapikey'
});
```
then it produces the error TypeError: require(...) is not a function.
I am using Nodejs version 18.12.1 LTS
Please help me

**Comment by terinjokes** [comment]
This is an error that the `require` function isn't defined in your environment. You're likely using JavaScript Modules and will need to import differently.
