### ISSUE TITLE
Firewall access rules for a zone

### ISSUE THREAD

**Issue by geoffreak** [cloudflare/node-cloudflare#15]
Any chance of the firewall access rules for a zone API being added to this library?
https://api.cloudflare.com/#firewall-access-rule-for-a-zone-list-access-rules

**Comment by Cherry** [comment]
Any progress on this being added? We'd love to see this included.

**Comment by terinjokes** [comment]
@Cherry This is a WIP change I might abandon, but can you give b6a097c58995dd087da4a4b7fddc4b43f340783a a shot and see if it works for you? Among other changes I'm trying out, it adds `accountAccessFirewall`, `userAccessFirewall`, and `zoneAccessFirewall` to the constructed client.

**Comment by terinjokes** [comment]
@Cherry Another ping to see if you can try out the pushed branch.

**Comment by Cherry** [comment]
Sorry for the delay Terin. I'll take a look at the changes this week and let you know how it goes.

**Comment by Cherry** [comment]
I finally had chance to test this, specifically the `zoneAccessFirewall` and `accountAccessFirewall` methods and they seem to work as expected. Thanks for the changes @terinjokes!

**Comment by terinjokes** [comment]
Great. I'll see to finishing the codegen and getting it out in a release soon.

**Comment by nosovk** [comment]
it seems that currently accountAccessFirewall is removed from master branch. Any plans to revive it?

**Comment by terinjokes** [comment]
I don't believe `accountAccessFirewall` was ever on master. I have no objections to merging it in if there's PRs.

**Comment by nosovk** [comment]
@terinjokes PR is done, could we merje?

**Comment by nosovk** [comment]
Another PR is done

**Comment by nosovk** [comment]
You may use this PR by adding 
```
"cloudflare": "github:cloudflare/node-cloudflare#pull/78/head"
```
to yours package.json
