### ISSUE TITLE
support for zone settings

### ISSUE THREAD

**Issue by neeksor** [cloudflare/node-cloudflare#18]
Hi,
Any plans to add support for updating the zone settings?
https://api.cloudflare.com/#zone-settings-edit-zone-settings-info

**Comment by terinjokes** [comment]
@neeksor Yes, we plan on supporting the entire API.

**Comment by hsingh6764** [comment]
Any update on time line?

**Comment by terinjokes** [comment]
As of v2.2.0:

* cf.zoneSettings.browse(zoneId)
* cf.zoneSettings.read(zoneId, settingId)
* cf.zoneSetting.edit(zoneId, settingId, params)
* cf.zoneSetting.editAll(zoneId, params)

**Comment by hsingh6764** [comment]
Thanks @terinjokes, that was fast. 
Please update docs when you get chance.
