### ISSUE TITLE
client.browseZones(): cannot set static values

### ISSUE THREAD

**Issue by dodekeract** [cloudflare/node-cloudflare#2]
**Disclaimer**: This may not be a bug, since this is my first attempt to use this API and I may have made some stupid mistake. (some simple examples on how to use this API would be really appreciated!)

### My Code

````javascript
var CloudFlare = require('cloudflare');

var client = new CloudFlare({
	email: 'email-address-for-dodekeract.report',
	key: 'somekey'
});

client.browseZones().then((response) => {
	console.log(response);
}).catch((error) => {
	console.log(error);
});
````

### Console Output

````
Error: Cannot set static values
    at Object.id (/home/dodekeract/code/dyndekeract/node_modules/verymodel/lib/model.js:347:27)
    at Object.<anonymous> (/home/dodekeract/code/dyndekeract/node_modules/verymodel/lib/model.js:450:43)
    at Array.forEach (native)
    at Object.model.loadData (/home/dodekeract/code/dyndekeract/node_modules/verymodel/lib/model.js:422:36)
    at Object.<anonymous> (/home/dodekeract/code/dyndekeract/node_modules/verymodel/lib/model.js:446:43)
    at Array.forEach (native)
    at Object.model.loadData (/home/dodekeract/code/dyndekeract/node_modules/verymodel/lib/model.js:422:36)
    at VeryModel.__dirname.create (/home/dodekeract/code/dyndekeract/node_modules/verymodel/lib/model.js:559:19)
    at /home/dodekeract/code/dyndekeract/node_modules/cloudflare/lib/zones.js:62:19
    at Array.map (native)
````

### Versions

````
$ node -v && npm list | grep cloudflare && lsb_release -a
v6.2.0
├─┬ cloudflare@1.0.0
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
````

**Comment by terinjokes** [comment]
@dodekeract I've fix it in a branch, but GitHub seems to still be acting up this morning, and the branch hasn't yet appeared in the UI and GitHub hasn't yet push the event to Travis to run CI.

**Comment by dodekeract** [comment]
Thanks, when can I expect a updated version on npm?

**Comment by terinjokes** [comment]
@dodekeract I'd prefer after CI runs, but might push it sooner if GitHub continues to be broken.

**Comment by dodekeract** [comment]
@terinjokes you may want to try to just push something else to the branch to re-trigger the CI integration.

**Comment by dodekeract** [comment]
@terinjokes it also seems like you could [open a pull-request or hit the refresh button in travis](http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit) to force Travis to run.

**Comment by terinjokes** [comment]
@dodekeract Should be good now, sorry about this issue.

**Comment by dodekeract** [comment]
@terinjokes no worries, I don't represent any huge company. Just using CF for my personal servers and trying to implement a dyndns service for my homeserver. Thanks for the fast resolution, it solved the issue on my side too.
