### ISSUE TITLE
Adopt icodeforlove/node-cloudflare as official interface

### ISSUE THREAD

**Issue by sheerun** [cloudflare/node-cloudflare#23]
Please don't take it personally :) 

Probably you'd be better releasing cloudflare v3 as (modified) version of `icodeforlove/node-cloudflare` instead of re-inventing the wheel. It's 1:1 with the API and has almost 100% coverage on functionality. This package has much different API (than official REST API) and supports very few methods.

**Comment by terinjokes** [comment]
Thanks for the feedback. Not taken personally.

The version here is designed after using (and writing) a number of API clients over the years, and aims to strike the right balance between feeling native and being easy to maintain. (v1, most certainly wasn't).

I've seen the other module, but it wasn't the direction I wanted to go here. You're welcome, of course, to continue using it.

**Comment by sheerun** [comment]
Here's what I currently use. Maybe you could add something like this to this library as it unleashes whole cloudflare API. Other methods could stay in backward-compatible way.

```es6
var got = require('got')

function cloudflare (config) {
  const headers = {
    'X-Auth-Email': config.email,
    'X-Auth-Key': config.key
  }

  async function request (url, params) {
    const result = await got(
      `https://api.cloudflare.com/client/v4/${url}`,
      Object.assign(
        {
          json: true,
          headers
        },
        params
      )
    )

    return result.body.result
  }

  return {
    get (url, query = {}) {
      return request(url, { method: 'GET', query })
    },
    delete: function (url, query = {}) {
      return request(url, { method: 'DELETE', query })
    },
    puts (url, body = {}) {
      return request(url, { method: 'PUT', body })
    },
    patch (url, body = {}) {
      return request(url, { method: 'PATCH', body })
    },
    post (url, body = {}) {
      return request(url, { method: 'POST', body })
    }
  }
}

```

**Comment by terinjokes** [comment]
What APIs do you use most? Aside from the two I already have tickets for, I don't know what to prioritize.

Obviously, the goal is all of them soon.

**Comment by sheerun** [comment]
Sincerely I think it doesn't matter and there should be a method to access any api endpoint, even after 1 minute after cloudflare released it. Not days, not weeks, and certainly not months after.
