### ISSUE TITLE
What is the syntax for "params" ?

### ISSUE THREAD

**Issue by hach3** [cloudflare/node-cloudflare#28]
Hello there ! Thanks for the creation of this api tool. I wan't to create a dnsRecord but I don't understand how to write the params. Can i eventually get an example ? Thanks for answer ! <3

**Comment by hach3** [comment]
https://github.com/cloudflare/node-cloudflare/issues/3

**Comment by hach3** [comment]
I finally chose to call a childProcess which is a npm package (child_process) and use directly the curl version from the cloudflare documentation, looks like : 

`childProcess('curl -X POST "https://api.cloudflare.com/client/v4/zones/:zone_record/dns_records" -H "X-Auth-Email: XXXX@XX.fr" -H "X-Auth-Key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -H "Content-Type: application/json" --data \'{"type":"CNAME","name":"' + username + '.ilikestream.com","content":"ilikestream.com","ttl":120,"proxied":true}\'', function(error, stdout, stderr) {
				console.log(error);
			});`

**Comment by terinjokes** [comment]
@hach3 "params" is the JSON object required by the API, which you can see an example of in the documentation. In this case.

```javascript
cf.dnsRecords.add({
  type: 'CNAME',
  name: username + '.ilikestream.com',
  content: 'ilikestream.com'.
  ttl: 120,
  proxied: true
});
```

There's definitely room for improvement to the documentation here.

**Comment by kedoska** [comment]
using version `2.4.1` 

#### Response code 400 (Bad Request) :boom: 

```javascript
    let resp = await cf.dnsRecords.add('SOME_ZONE_ID', {
      type: 'CNAME',
      name: 'some.domain.ext',
      content: '1.1.1.1', 
      proxied: true,
    })
```

However, the same `zone` and `credentials` works with other methods like `cf.dnsRecords.browse`.
@terinjokes in your example above you are not specifying the `zone`. Is that possible (to omit the zone id)?

**Comment by terinjokes** [comment]
No, zone ID is required for DNS operations, my example above is wrong.
