### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by spencercharest** [cloudflare/node-cloudflare#34]
Some methods like `.dnsRecords.browse()` return paginated results with a property `result_info` that looks some like this.

```
{ 
     page: 1,
     per_page: 20,
     total_pages: 2,
     count: 20,
     total_count: 24 
}
```

Is it possible to paginate or return all results at once?

**Comment by terinjokes** [comment]
Optional parameters can be provided after the required parameters. In this case, as the second parameter after the zone id:

```javascript
cf.dnsRecords.browse('023e105f4ecef8ad9ca31a8372d0c353', {
	page: 2,
	per_page: 100
});
```

**Comment by AdrieanKhisbe** [comment]
Would be great if there is a clue about it in the readme or tthe generated jsdoc :)

**Comment by terinjokes** [comment]
@AdrieanKhisbe I ran into a bug that prevented me from adding to the jsdoc, but keep an eye out, and add once it's resolved.
