### ISSUE TITLE
Retry API calls

### ISSUE THREAD

**Issue by naseemkullah** [cloudflare/node-cloudflare#49]
Occasionally we will get a bad request error from an api call to purge the cache. However upon retrying the same request immediately after, it succeeds.

Could a retry policy be implemented directly in the Cloudflare API? 
For the `zones.purgeCache` in particular.

**Comment by terinjokes** [comment]
It would be possible to add, but not currently planned. I don't currently have any way to make most requests to the API idempotent, so it would be unsafe for me to do so automatically.

**Comment by naseemkullah** [comment]
Sorry, I do not understand the need for idempotency if the API request is only to succeed once? The retry mechanism would only be upon failure of a request after all.

Is that to say there are requests that could be partially complete and then error out?

**Comment by terinjokes** [comment]
You use the package to submit a request. Most of the time it succeeds and we're all happy.

However it fails. Say your network gets disconnected, or you get a 502 from some HTTP proxy somewhere on Cloudflare's backend, you as the client (and me as the package author) have no way to know if it's been processed or not. Other API have idempotency guarantees (either that retries are safe, or using idempotency keys), but the Cloudflare API does not.

With that mind, it's not the right place for me to make the decision to retry or not.

**Comment by naseemkullah** [comment]
I see, I see.
Could it be user configurable option that defaults to false/0 retries?

**Comment by terinjokes** [comment]
I plan on exposing this as part of the v3 API.

**Comment by naseemkullah** [comment]
Thanks! no rush for this one :) at least not from me!
