### ISSUE TITLE
Two read methods on ZoneWorkersScripts

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [cloudflare/node-cloudflare#51]
I was going through the docs and noticed that at [ZoneWorkersScripts ](https://cloudflare.github.io/node-cloudflare/#zoneworkersscript)there are two `read` methods, the first taking just a zone ID, and the second taking a zone ID and a script. And there seems to be some additional typos in that section as well.

**Comment by HeyITGuyFixIt** [comment]
It is also deprecated in the Cloudflare API.

**Comment by terinjokes** [comment]
The Workers API has changed a lot, so there's "two" versions in the API. As for the documentation, it's currently generated from JSDoc blocks, and I suspect there's a copy and paste typo.

A PR is accepted to find and fix the typo.
