### ISSUE TITLE
Dependencies upgrade

### ISSUE THREAD

**Issue by artursudnik** [cloudflare/node-cloudflare#55]
Hi,

Is dependencies upgrade planned? I am getting following warning.

(node:3640) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated.

Apparently this is caused by very old version of "get" package.

Anyway, many other dependencies are quite outdated and npm install executed on this repo clone reports many vulnerabilities.

**Comment by terinjokes** [comment]
Hey,

Upgrades of dependencies are planned, just not finished yet.

**Comment by Pavlovich4** [comment]
Hi @terinjokes 

any update about the upgrade of dependencies ? I am getting the same message.

**Comment by terinjokes** [comment]
There's no version of the `got` dependency where this message is fixed that doesn't also break their API. Since the `got` API leaks through a lot, it's not feasible to upgrade without also having a breaking change ourselves.

**Comment by justinasfour04** [comment]
@terinjokes you talk about `got` API leaking through a lot. Can you elaborate please? Why can't this project use the latest version of `got`?

**Comment by sadtaco** [comment]
What's wrong with making a breaking change?  People on old versions of node can just use the older version of the module.
Also, getHeaders() is supported all the way back to version 8.

**Comment by terinjokes** [comment]
@sadtaco It's more difficult both for us developing this package and for users. Especially since the "breaking change" isn't just changing the version number in package.json: newer versions of got are very different.

**Comment by vkentta** [comment]
As a workaround one can use node v10. Would love to get the fix though :smiling_face_with_three_hearts:

**Comment by terinjokes** [comment]
@vkentta this is believed to be fixed in 2.8.0

**Comment by Sv443** [comment]
Are there any updates on this?  
I'd hate delivering my software while these warnings are spammed to the console.

**Comment by terinjokes** [comment]
I'm working on a 3.0 that stops using `got`, until then there's no good way for me to fix this.

**Comment by michakfromparis** [comment]
Any update on this ? Thanks for doing your best.

**Comment by mikejpoole** [comment]
Hi @terinjokes many thanks for your work on this.
Do you have a rough idea of when the deprecated `_headers` will be replaced?

**Comment by kjschulz** [comment]
Any update on this deprecation warning issue...it's literally 2.5 yrs old ? 😂

**Comment by lexuzieel** [comment]
Still getting this warning on node 18. Maybe somebody have made a fork with the fix or could point out how to fix it so I could update it and share the fork myself?

**Comment by artursudnik** [comment]
Wow... It is still not fixed. Impressive...

**Comment by aishwat** [comment]
It's gonna be 4th year anniversary for this issue 🎉 😅
