### ISSUE TITLE
Https-proxy-agent needs updating

### ISSUE THREAD

**Issue by justinasfour04** [cloudflare/node-cloudflare#57]
We are using cloudflare-node version 2.7.0 and cannot use got due to the related issue.
cloudflare has a dependency that needs updating
cloudflare@2.7.0
  └─┬ https-proxy-agent@2.2.4
    └── agent-base@4.3.0

related issue:
https://github.com/sindresorhus/got/issues/1039

**Comment by terinjokes** [comment]
That's unfortunate. It definitely worked when I implemented it.

I've added this to my todo list.

**Comment by justinasfour04** [comment]
@terinjokes Is this PR going to get updated #54 ?

**Comment by terinjokes** [comment]
I'm unsure, I'll be able to take a look this weekend.

**Comment by naseemkullah** [comment]
@terinjokes we are at a fork in road here, we believe in OSS and love this lib but if it cannot be maintained a little more we will use the cloudflare API directly as it is a current blocker.

With that said how do you feel about adding @justinasfour04  (or someone else) as a maintainer of this lib and making it more of a communal effort, considering it is not an official Cloudflare product?

**Comment by terinjokes** [comment]
I started working on this over the weekend. Unfortunately, I ran out of time before completing it. I plan on continuing this week.

**Comment by naseemkullah** [comment]
Thanks @terinjokes

**Comment by justinasfour04** [comment]
Just out of curiosity why did you not answer the question that @naseemkullah asked about adding on more maintainers to the project?

**Comment by terinjokes** [comment]
Pull requests are accepted, but at this time I don't plan on adding additional maintainers. I suspect this will change in the future.

**Comment by justinasfour04** [comment]
I removed this library from my project and `got` works. Not sure what the status is on the fix but for now you lost a developer using this library

**Comment by terinjokes** [comment]
This is being removed in the next version, 3.0.0 which you can track in the [3.0.0 milestone](https://github.com/cloudflare/node-cloudflare/milestone/1)

**Comment by justinasfour04** [comment]
oh nice ok. I'll keep my eye out

**Comment by terinjokes** [comment]
Can someone encountering this issue, and still using this library, take a look at the fix proposed in #67 and confirm it works in their environment?

**Comment by Stono** [comment]
Hey folks, any change we could get some traction on this?  It causes us quite a bit of pain.  Alex has done the work in the PR and tested it on our apps that use this library at AutoTrader, i'm not sure what else we need to do?

**Comment by naseemkullah** [comment]
> I removed this library from my project and `got` works. Not sure what the status is on the fix but for now you lost a developer using this library

Just to clarify, we no longer use the lib and are not planning to go back for the time being, as such we are no longer in a place to comment about it.
