### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by terinjokes** [cloudflare/node-cloudflare#58]
The Cloudflare API is pretty consistent in how it supports pagination. It would be nice to have to support asynchronously fetching new pages.

#34 #37

**Comment by depombo** [comment]
That would be great!

**Comment by ririko5834** [comment]
Can you fetch all DNS records in one request without pagination?

**Comment by terinjokes** [comment]
Not at this time.

**Comment by mikejpoole** [comment]
I would also be very grateful if either there could be larger paging or pagination as at the moment we are having to store all the zone IDs in our own database because `zones.browse()` only returns the first 20 zones.

**Comment by terinjokes** [comment]
The last parameter, after all the URL parameters and body, is and optional query parameter object, so you should be able to pass `{ page: 2 }`

**Comment by mikejpoole** [comment]
Ohh that is handy @terinjokes . I've tried that out and it works like a charm. 
Does that mean that any `browse` method will accept an options object in the same manner and that we could also pass an options object to a `read` method after the ID? e.g. `pageRules.read('abc123', { status: active })`.

**Comment by terinjokes** [comment]
All the methods should allow setting query parameters as the last (optional) function parameter, though the `browse` and `read` ones are probably the most useful.

**Comment by mikejpoole** [comment]
Thanks for confirming that @terinjokes . The biggest benefit is that I can simply return a named zone `pageRules.browse( { name: 'foo.com' } )` effectively using the `browse` method as a read method.

For the benefit of others [here are all the optional parameters](https://api.cloudflare.com/#zone-list-zones) you could pass into the `zones.browse()` method.
