### ISSUE TITLE
addDNS doesn't accept all valid params

### ISSUE THREAD

**Issue by brod** [cloudflare/node-cloudflare#6]
Is there any reason that the `addDNS()` function only passes `[type, name, content, ttl]` to the body? The following record is valid and avoids the extra step of editing the newly created record.

example `DNSrecord`
````
DNSRecord.create({
    type: 'A',
    name: 'test.website.com',
    content: '1.2.3.4',
    proxied: true,
    zone_id: 'xxx'
})
````
https://github.com/cloudflare/node-cloudflare/blob/084ec1500b015124184ca16f9853766593837f4a/lib/dns.js#L98

**Comment by terinjokes** [comment]
@brod Because those are the only four parameters listed [in the documentation](https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record) as being valid.

**Comment by brod** [comment]
Fair enough

**Comment by sielay** [comment]
According to you support `proxied` should be supported and is supported by API
