### ISSUE TITLE
Implement TypeScript Client

### ISSUE THREAD

**Issue by terinjokes** [cloudflare/node-cloudflare#62]
To help aid in better documentation and autocomplete in editors (#59), I'd like to begin to using TypeScript. Packages pushed to npm would be compiled to JavaScript and include the "*.d.ts" files.

This is mostly a tracking ticket for this work.

**Comment by mastermunj** [comment]
Hi @terinjokes,

I've attempted creating a [TypeScript client for Cloudflare API](https://github.com/mastermunj/cloudflare-api). As of now only user & user-token APIs are created and test cases are added for the same as well.

I know the code needs quite a lot of work for being better organized & tested, however, I wanted to share it with you in case if it makes sense to use it as a base or maybe if there's a way I could contribute towards the approach you are going ahead with.

The approach I have taken is
* To be as verbose as possible to make the APIs developer-friendly.
* Mimic the actual API endpoints for easy usage.
e.g. User Token Details can be called as `cf.userToken.details(identifier);`.
* Document generated with [TypeDoc](https://typedoc.org) will also adhere to API documentation.
* I am also planning to add validation for all inputs.

**Comment by Maxpain177** [comment]
Any news?

**Comment by depombo** [comment]
> Any news?

Ditto

**Comment by terinjokes** [comment]
We should have TypeScript support in the next major version of this client, which is redesigned to be easier to update.

I'll accept contributions to this version.

**Comment by robd** [comment]
Not sure if this work is still planned, but for folks coming to this issue, another alternative is Pulumi which has typescript bindings (plus other languages) https://www.pulumi.com/docs/intro/cloud-providers/cloudflare/

**Comment by terinjokes** [comment]
Yep, still planned.

**Comment by rawpixel-vincent** [comment]
Not sure if it's related but currently the client initialization causes a type error:
```
Value of type 'typeof Cloudflare' is not callable. Did you mean to include 'new'?ts(2348)
```
with the code:
```javascript
const cloudflare = require('cloudflare')({
    email: 'email',
    key: 'key',
  });
```

Couldn't find a workaround.

**Comment by terinjokes** [comment]
I'm in the proccess of generating clients we can better support from our new OpenAPI schemas. I don't have any news on when they'll be available, but it is being worked on.

**Comment by Dennis4720** [comment]
I also need to use the API preferably with typescript support. Please let me know when there's an ETA =).
