### ISSUE TITLE
zoneSettings.edit fails because it's not JSON

### ISSUE THREAD

**Issue by TheLQ** [cloudflare/node-cloudflare#83]
This script using 2.7.0, 2.8.0, and master

```
var cf = require('cloudflare')({
    email: "xxx",
    key: "xxx"
    // this doesn't work either
    // token: 'xxx'
  });


cf.zoneSettings.edit("xxx", "always_use_https", "on")
  .then((res) => {
      console.log("res", res)
  }).catch(e => {throw e})
```

Fails with

```
ErrorClass [HTTPError]: Response code 400 (Bad Request)
    at //wwwman/node_modules/got/index.js:123:13
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  host: 'api.cloudflare.com',
  hostname: 'api.cloudflare.com',
  method: 'PATCH',
  path: '/client/v4/zones/xxx/settings/always_use_https',
  statusCode: 400,
  statusMessage: 'Bad Request'
}
```

Adding some logging to the Got library (since the error doesn't have the body) shows it just sends "on" to that URL,  the API is returning a JSON parsing error. 

```
req opts {
  protocol: 'https:',
  path: '/client/v4/zones/xxx/settings/always_use_https',
  host: 'api.cloudflare.com',
  hostname: 'api.cloudflare.com',
  pathname: '/client/v4/zones/xxx/settings/always_use_https',
  href: 'https://api.cloudflare.com/client/v4/zones/xxx/settings/always_use_https',
  json: true,
  method: 'PATCH',
  headers: {
    'user-agent': 'cloudflare/2.8.0 node/15.5.1',
    'accept-encoding': 'gzip,deflate',
    'content-type': 'application/json',
    accept: 'application/json',
    'x-cloudflare-client-user-agent': '{"bindings_version":"2.8.0","lang":"node","lang_version":"v15.5.1","platform":"linux","arch":"x64","publisher":"cloudflare"}',
    'x-auth-key': 'xxx',
    'x-auth-email': 'xxx',
    'content-length': 3
  },
  body: 'off',
....
}
res body {
  success: false,
  errors: [ { code: 6007, message: 'Malformed JSON in request body' } ],
  messages: [],
  result: null
}
```

**Comment by onceuponapriori** [comment]
I was very surprised this behavior too, here's what worked for me:

```
cf.zoneSettings.edit('XXXMYZONEID', 'security_level', '{"value":"medium"}').then(function (resp) {
  var s = resp;

  console.log(s);
});
```

I assumed of course that the API would construct the appropriate JSON object for me since the docs say it accepts a string, but it looks like by design or otherwise they'd like you to pass a JSON string.

**Comment by terinjokes** [comment]
Yep, looks like this is a typo made when manually transcribing the page into code in this repository.

**Comment by onceuponapriori** [comment]
Thanks for clarifying @terinjokes. Just to confirm, are you saying that the intended behavior is that just passing `"medium"` should work, and thus it is a functional bug? Or is the intended behavior that one must use `'{"value":"medium"}'` and so it is more of a documentation bug?

In any case, I recommend putting at least one sample `edit` command requiring multiple parameters on the project homepage. I think that would go a long way toward helping folks who are just starting out.
