### ISSUE TITLE
Please publish 2.8.0

### ISSUE THREAD

**Issue by dphrag** [cloudflare/node-cloudflare#87]
The current version of this on NPM is 2.7.0, next is 2.8.0, which simply includes a bump to http-proxy-agent.

I spent days trying to figure out why some completely unrelated issue was having problems, and it turns out the *mere existence* of an older version of **agent-base** will break other libraries. I found that solution in this random unrelated comment over here, for example: https://github.com/AzureAD/passport-azure-ad/issues/522

Forcing the resolution of http-proxy-agent fixed my issue, but this was actually the only package that caused the issue, and 2.8.0 fixes it. Please publish it to avoid other devs having to go on this goose chase! haha :)

**Comment by terinjokes** [comment]
It is published: http://registry.npmjs.com/cloudflare/2.8.0

**Comment by dphrag** [comment]
Yes, it is available on npm, but only with a version specific request. The current default release is 2.7.0. Sorry, I should change the ticket name to "make default release 2.7.0"

**Comment by threepointone** [comment]
This appears to have been fixed?
