### ISSUE TITLE
Please add support for pages

### ISSUE THREAD

**Issue by PringlePot** [cloudflare/node-cloudflare#92]
It would be cool to have support for pages using this api.

**Comment by Fomin2402** [comment]
plus one

**Comment by terinjokes** [comment]
We're in the process of updating this project based on schemas.

**Comment by IanVS** [comment]
OK great, can you give any estimated timeline of when it might be complete?  Trying to decide how best to proceed in my own usage.

**Comment by terinjokes** [comment]
Likely shortly after the holiday break.
