### ISSUE TITLE
Deprecated  workers/filters for Zone Worker Routes

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [cloudflare/node-cloudflare#96]
According to the latest documentation of v4 Cloudflare Api 
```
https://api.cloudflare.com/#worker-filters-deprecated
```
And has been shifted to 
```
https://api.cloudflare.com/#worker-routes-properties
```

Due to this I am unable to connect my worker to the pattern.

**Comment by JWesorick** [comment]
This is not in a release yet right? Looks like its only in master.

**Comment by harrisonlo** [comment]
@terinjokes would you publish this to npm?
