### ISSUE TITLE
cf.zoneSettings.editAll not works as excepted

### ISSUE THREAD

**Issue by leepood** [cloudflare/node-cloudflare#98]
Version: 2.9.1

```
zoneSettings.editAll(id, {
              ssl: { value: 'flexible' },
              always_use_https: { value: 'on' },
})
.then(resp => console.log(resp))
.catch(err => console.log(err))

```

Show Error

```
code: 1004, message: Missing 'items'
```

**Comment by terinjokes** [comment]
I believe you need to call it with an array of setting objects.

```javascript
zoneSettings.editAll(id, {
  items: [
    {id: "ssl", value: "flexible"},
    {id: "always_use_https", value: "on"}
  ]
})
```

**Comment by leepood** [comment]
> I believe you need to call it with an array of setting objects.
> 
> ```js
> zoneSettings.editAll(id, {
>   items: [
>     {id: "ssl", value: "flexible"},
>     {id: "always_use_https", value: "on"}
>   ]
> })
> ```

okay, thanks
