### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by ririko5834** [cloudflare/node-cloudflare#99]
When I want to create DNS record or delete DNS record I am getting `Response code 403 (Forbidden) `

I am using `cloudflare.dnsRecords.add()` and `cloudflare.dnsRecords.del()` methods. 

My API token perms: 
![image](https://user-images.githubusercontent.com/64729293/135092036-0355cd6f-a03c-426d-b7ef-740c032361fb.png)

**Comment by terinjokes** [comment]
Do you have a code snippet that reproduces the problem?

**Comment by ririko5834** [comment]
When I want to create or delete a DNS record, I get an error `Response code 403 (Forbidden)`. When I view DNS records, it works and I don't get any error. I have an API token with permissions DNS:Edit and Zone:Edit. So what could be the problem?

**Comment by ririko5834** [comment]
I know why it shows, when I called API endpoint with CURL, I got this error
```
{
    "result": null,
    "success": false,
    "errors": [{
        "code": 1038,
        "message": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
    }],
    "messages": []
}
```


The API wrapper's error catching should be improved, really high priority.
